# Fish shell completions for the dot command
# Auto-generated by `dot completions`

complete -c dot -f

# Top-level commands
complete -c dot -n "__fish_use_subcommand" -a "init" -d "Full setup: brew, packages, stow, settings"
complete -c dot -n "__fish_use_subcommand" -a "stow" -d "Create symlinks with GNU Stow"
complete -c dot -n "__fish_use_subcommand" -a "unstow" -d "Remove symlinks"
complete -c dot -n "__fish_use_subcommand" -a "update" -d "Pull repo and run init"
complete -c dot -n "__fish_use_subcommand" -a "doctor" -d "Check installation health"
complete -c dot -n "__fish_use_subcommand" -a "edit" -d "Open dotfiles in editor"
complete -c dot -n "__fish_use_subcommand" -a "package" -d "Manage packages"
complete -c dot -n "__fish_use_subcommand" -a "merge" -d "Merge config files (*.base.json)"
complete -c dot -n "__fish_use_subcommand" -a "service" -d "Manage brew services"
complete -c dot -n "__fish_use_subcommand" -a "pmset" -d "Manage power settings"
complete -c dot -n "__fish_use_subcommand" -a "defaults" -d "Manage macOS defaults"
complete -c dot -n "__fish_use_subcommand" -a "keyboard" -d "Manage keyboard remappings"
complete -c dot -n "__fish_use_subcommand" -a "backup" -d "Backup existing configs"
complete -c dot -n "__fish_use_subcommand" -a "restore" -d "Restore configs from backup"
complete -c dot -n "__fish_use_subcommand" -a "benchmark-shell" -d "Benchmark Fish startup performance"
complete -c dot -n "__fish_use_subcommand" -a "completions" -d "Generate Fish shell completions"
complete -c dot -n "__fish_use_subcommand" -a "link" -d "Install dot command globally"
complete -c dot -n "__fish_use_subcommand" -a "unlink" -d "Remove global dot command"
complete -c dot -n "__fish_use_subcommand" -a "help" -d "Show help message"

# stow options
complete -c dot -n "__fish_seen_subcommand_from stow" -s c -l clean -d "Remove dirs before stowing"

# package subcommands
complete -c dot -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from add remove install list" -a "add" -d "Add a package"
complete -c dot -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from add remove install list" -a "remove" -d "Remove a package"
complete -c dot -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from add remove install list" -a "install" -d "Install packages from profile"
complete -c dot -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from add remove install list" -a "list" -d "List all packages"

# package profile/type flags
complete -c dot -n "__fish_seen_subcommand_from package" -l personal -d "Target personal profile files"
complete -c dot -n "__fish_seen_subcommand_from package" -l work -d "Target work profile files"
complete -c dot -n "__fish_seen_subcommand_from package" -l npm -d "Target npm (Bun global) packages"

# service subcommands
complete -c dot -n "__fish_seen_subcommand_from service" -a "start" -d "Start services from services.json"
complete -c dot -n "__fish_seen_subcommand_from service" -a "list" -d "List configured and running services"

# apply/show subcommands for settings commands
complete -c dot -n "__fish_seen_subcommand_from pmset" -a "apply show" -d "apply or show"
complete -c dot -n "__fish_seen_subcommand_from defaults" -a "apply show" -d "apply or show"
complete -c dot -n "__fish_seen_subcommand_from keyboard" -a "apply show" -d "apply or show"

# restore options
complete -c dot -n "__fish_seen_subcommand_from restore" -l list -d "List backup contents"
complete -c dot -n "__fish_seen_subcommand_from restore" -l merge -d "Restore only files not in repo"

# benchmark-shell options
complete -c dot -n "__fish_seen_subcommand_from benchmark-shell" -s r -l runs -d "Number of benchmark runs" -xa "5 10 15 20 25 30"
complete -c dot -n "__fish_seen_subcommand_from benchmark-shell" -s v -l verbose -d "Show detailed timing per run"

# Dynamic completion: installed brew packages (for package remove)
function __dot_installed_packages
    if command -q brew
        brew list --formula 2>/dev/null
        brew list --cask 2>/dev/null
    end
end
complete -c dot -n "__fish_seen_subcommand_from package; and __fish_seen_subcommand_from remove" -xa "(__dot_installed_packages)"
